name: Monitor Commits

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-commit-changes:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the monitored repository
        uses: actions/checkout@v3
        with:
          repository: vercel/next.js
          ref: canary
          fetch-depth: 0

      - name: Download last checked commit artifact
        uses: actions/download-artifact@v4
        with:
          name: last_checked_commit
          path: last_checked_commit
        continue-on-error: true

      - name: Load the last checked commit
        id: load_last_commit
        run: |
          if [ -f last_checked_commit ]; then
            LAST_CHECKED_COMMIT=$(cat last_checked_commit)
          else
            echo "Artifact not found. Using the latest commit."
            LAST_CHECKED_COMMIT=$(git rev-parse HEAD)
          fi
          echo "Last checked commit: $LAST_CHECKED_COMMIT"
          echo "LAST_CHECKED_COMMIT=$LAST_CHECKED_COMMIT" >> $GITHUB_ENV

      - name: Check for changes in docs/
        id: check_changes
        run: |
          # 最新のコミットSHAを取得
          LATEST_COMMIT=$(git rev-parse HEAD)

          # 差分を計算
          CHANGED_FILES=$(git diff --name-only $LAST_CHECKED_COMMIT $LATEST_COMMIT)
          CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')

          echo "Changed files: $CHANGED_FILES"
          echo "COMMIT_SHA=$LATEST_COMMIT" >> $GITHUB_ENV
          if echo "$CHANGED_FILES" | grep -q '^docs/'; then
            echo "DOCS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "DOCS_CHANGED=false" >> $GITHUB_ENV
          fi

          echo $COMMIT_SHA > last_checked_commit

      - name: Notify Slack if changes detected
        if: ${{ env.DOCS_CHANGED == 'true' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          payload: |
            {
              "text": "Changes detected in the 'docs/' directory of 'vercel/next.js'",
              "attachments": [
                {
                  "text": "Check the changes here: https://github.com/vercel/next.js/compare/${{ env.LAST_CHECKED_COMMIT }}...${{ env.COMMIT_SHA }}",
                  "color": "#36a64f"
                }
              ]
            }

      - name: Save the latest commit as artifact
        if: ${{ env.DOCS_CHANGED == 'true' || true }}
        uses: actions/upload-artifact@v4
        with:
          name: last_checked_commit
          path: last_checked_commit
