name: Monitor Commits

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-commit-changes:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the monitored repository
        uses: actions/checkout@v3
        with:
          repository: vercel/next.js
          ref: canary
          fetch-depth: 0

      - name: Download the last checked commit artifact
        uses: actions/download-artifact@v4
        with:
          name: last_checked_commit
          path: last_checked_commit
        continue-on-error: true

      - name: Load the last checked commit
        id: load_last_checked_commit
        run: |
          if [ -f last_checked_commit/commit ]; then
            LAST_CHECKED_COMMIT=$(cat last_checked_commit/commit)
          else
            LAST_CHECKED_COMMIT=$(git rev-parse HEAD)
          fi

          echo "Last checked commit: $LAST_CHECKED_COMMIT"
          echo "LAST_CHECKED_COMMIT=$LAST_CHECKED_COMMIT" >> $GITHUB_ENV

      - name: Check for changes in docs/
        id: check_docs_changes
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "Latest commit: $LATEST_COMMIT"

          CHANGED_FILES=$(git diff --name-only $LAST_CHECKED_COMMIT $LATEST_COMMIT)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^docs/"; then
            echo "Changes in docs/ detected"
            echo "DOCS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in docs/ detected"
            echo "DOCS_CHANGED=false" >> $GITHUB_ENV
          fi

          echo "$LATEST_COMMIT" > last_checked_commit/commit

      - name: Notify Slack if docs/ changed
        if: env.DOCS_CHANGED == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "Changes in docs/ detected in vercel/next.js"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "Changes in `docs/` detected in `vercel/next.js`"

      - name: Upload the last checked commit artifact
        uses: actions/upload-artifact@v4
        with:
          name: last_checked_commit
          path: last_checked_commit
