name: Monitor Commits

on:
  schedule:
    # 1時間ごとに実行
    - cron: "0 * * * *"
  workflow_dispatch: # 手動でのトリガーも可能

jobs:
  check-commit-changes:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the monitored repository
        uses: actions/checkout@v3
        with:
          repository: vercel/next.js # 監視対象のリポジトリ
          ref: canary # 対象ブランチ

      - name: Check for changes in docs/
        id: check_changes
        run: |
          git fetch
          LAST_COMMIT=$(git rev-parse HEAD)
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $LAST_COMMIT)

          echo "Last commit files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^docs/'; then
            echo "docs_changed=true" >> $GITHUB_ENV
          else
            echo "docs_changed=false" >> $GITHUB_ENV
          fi

      - name: Notify Slack if changes detected
        if: env.docs_changed == 'true'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          payload: |
            {
              "text": "Changes detected in the 'docs/' directory of 'vercel/next.js'",
              "attachments": [
                {
                  "text": "Check the latest commit: https://github.com/vercel/next.js/commit/${{ github.sha }}",
                  "color": "#36a64f"
                }
              ]
            }
