name: Monitor Commits

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-commit-changes:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      id-token: write
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Checkout the monitored repository
        uses: actions/checkout@v3
        with:
          repository: vercel/next.js
          ref: canary
          fetch-depth: 0

      - name: Restore last checked commit from cache
        id: restore_cache
        uses: actions/cache/restore@v4
        with:
          path: last_checked_commit
          key: last-checked-commit

      - name: Load the last checked commit
        id: load_last_checked_commit
        run: |
          if [ -f last_checked_commit/commit ]; then
            LAST_CHECKED_COMMIT=$(cat last_checked_commit/commit)
          else
            LAST_CHECKED_COMMIT=$(git rev-parse HEAD)
          fi

          echo "Last checked commit: $LAST_CHECKED_COMMIT"
          echo "LAST_CHECKED_COMMIT=$LAST_CHECKED_COMMIT" >> $GITHUB_ENV

      - name: Check for changes in docs/
        id: check_docs_changes
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "Latest commit: $LATEST_COMMIT"

          CHANGED_FILES=$(git diff --name-only $LAST_CHECKED_COMMIT $LATEST_COMMIT)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^docs/"; then
            echo "Changes in docs/ detected"
            echo "DOCS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in docs/ detected"
            echo "DOCS_CHANGED=false" >> $GITHUB_ENV
          fi

          mkdir -p last_checked_commit
          echo "$LATEST_COMMIT" > last_checked_commit/commit
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV

      - name: Notify Slack if docs/ changed
        if: env.DOCS_CHANGED == 'true'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "Changes in docs/ detected in vercel/next.js. Check it out here: https://github.com/vercel/next.js/compare/{{ $LAST_CHECKED_COMMIT }}...{{ $LATEST_COMMIT }}"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "Changes in `docs/` detected in `vercel/next.js`. Check it out <https://github.com/vercel/next.js/compare/${{ env.LAST_CHECKED_COMMIT }}...${{ env.LATEST_COMMIT }}|here>."

      - name: Checkout own repository
        uses: actions/checkout@v3

      - name: Delete existing cache
        run: gh cache delete last-checked-commit || echo "Cache not found"

      - name: Save last checked commit to cache
        uses: actions/cache/save@v4
        with:
          path: last_checked_commit
          key: last-checked-commit
